---
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern : kafka.server<type=ReplicaManager, name=(.+)><>(Value|OneMinuteRate)
    name: "cp_kafka_server_replicamanager_$1"
  - pattern : kafka.controller<type=KafkaController, name=(.+)><>Value
    name: "cp_kafka_controller_kafkacontroller_$1"
  - pattern : kafka.server<type=BrokerTopicMetrics, name=(.+)><>OneMinuteRate
    name: "cp_kafka_server_brokertopicmetrics_$1"
  - pattern : kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>OneMinuteRate
    name: "cp_kafka_network_requestmetrics_requestspersec_$1"
  - pattern : kafka.network<type=SocketServer, name=NetworkProcessorAvgIdlePercent><>Value
    name: "cp_kafka_network_socketserver_networkprocessoravgidlepercent"
  - pattern : kafka.server<type=ReplicaFetcherManager, name=MaxLag, clientId=(.+)><>Value
    name: "cp_kafka_server_replicafetchermanager_maxlag_$1"
  - pattern : kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>OneMinuteRate
    name: "cp_kafka_kafkarequesthandlerpool_requesthandleravgidlepercent"
  - pattern : kafka.controller<type=ControllerStats, name=(.+)><>OneMinuteRate
    name: "cp_kafka_controller_controllerstats_$1"
  - pattern : kafka.server<type=SessionExpireListener, name=(.+)><>OneMinuteRate
    name: "cp_kafka_server_sessionexpirelistener_$1"
  - pattern : kafka.server<type=Produce,user=([-.\w]+),client-id=([-.\w]+)><>(\w+)
    name: "cp_kafka_server_throttle_produce_$1_$2_$3"
  - pattern : kafka.server<type=Fetch,user=([-.\w]+),client-id=([-.\w]+)><>(\w+)
    name: "cp_kafka_server_throttle_fetch_$1_$2_$3"
